### ISSUE TITLE
Write tests for generateResponsiveImages function

### ISSUE THREAD

**Issue by eyvazahmadzada** [joomla-projects/gsoc21_media-manager#2]
### Task (Week 1)
Tests for **generateResponsiveImages** method of **Image** class

### About
Write unit tests for generateResponsiveImages function for different situations.

**Comment by fancyFranci** [comment]
It is really really good, that you plan to write tests! Please include them directly in the other issue (and its description). This way we avoid the creation of technical depts ("I write the tests later, when I have time"), because the tests become a part of the feature and not a nice-to-have :)

**Comment by eyvazahmadzada** [comment]
@fancyFranci Thanks for your comment :) It's done.
